# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 22:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Duenger',
                'verbose_name_plural': 'Duenger',
            },
        ),
        migrations.CreateModel(
            name='Duengungsstufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Duengungsstufe',
                'verbose_name_plural': 'Duengungsstufe',
            },
        ),
        migrations.CreateModel(
            name='Familie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Familie',
                'verbose_name_plural': 'Familien',
            },
        ),
        migrations.CreateModel(
            name='Kultur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('familie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kulturen', to='jordbruksmark.Familie')),
            ],
            options={
                'verbose_name': 'Kultur',
                'verbose_name_plural': 'Kulturen',
            },
        ),
        migrations.CreateModel(
            name='Parzelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Parzelle',
                'verbose_name_plural': 'Parzellen',
            },
        ),
        migrations.CreateModel(
            name='Satz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField(verbose_name='Nummer')),
                ('sorte', models.CharField(max_length=200, verbose_name='Sorte')),
                ('anzucht', models.IntegerField(blank=True, null=True, verbose_name='Anzucht')),
                ('g_pro_tausend', models.FloatField(blank=True, null=True, verbose_name='g/1000 Pflanzen')),
                ('anzahl_anzucht', models.IntegerField(blank=True, null=True, verbose_name='Anz. Anzucht')),
                ('setzen', models.IntegerField(blank=True, null=True, verbose_name='Setzen')),
                ('g_pro_aare', models.IntegerField(blank=True, null=True, verbose_name='g/Are')),
                ('saat', models.IntegerField(blank=True, null=True, verbose_name='Saat')),
                ('erste_ernte', models.IntegerField(blank=True, null=True, verbose_name='1. Ernte')),
                ('ernteschluss', models.IntegerField(blank=True, null=True, verbose_name='Ernteschluss')),
                ('duenger_kg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duenger kg 10N')),
                ('beet_breite', models.FloatField(blank=True, null=True, verbose_name='g/1000 Pflanzen')),
                ('reihen_abstand', models.IntegerField(blank=True, null=True, verbose_name='Reihenabstand')),
                ('pflanz_abstand', models.IntegerField(blank=True, null=True, verbose_name='Pflanzabstand')),
                ('ertrag_erwartung', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ertrag kg/m2')),
                ('bemerkung', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Allg. Bemerkungen')),
                ('bem_anzucht', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Bem.  Anzucht')),
                ('bem_setzen', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Bem. Setzen')),
                ('bem_saat', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Bem. Direktsaat')),
                ('duenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saetze', to='jordbruksmark.Duenger')),
                ('duengungsstufe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saetze', to='jordbruksmark.Duengungsstufe')),
                ('kultur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saetze', to='jordbruksmark.Kultur')),
                ('parzelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saetze', to='jordbruksmark.Parzelle')),
            ],
            options={
                'verbose_name': 'Satz',
                'verbose_name_plural': 'Saetze',
            },
        ),
    ]
