# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jordbruksmark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wochen_Menge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woche', models.IntegerField(verbose_name='Wochennummer')),
                ('menge', models.IntegerField(verbose_name='Menge')),
                ('kultur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kulturen', to='jordbruksmark.Kultur')),
            ],
            options={
                'verbose_name': 'Kultur',
                'verbose_name_plural': 'Kulturen',
            },
        ),
        migrations.AlterModelOptions(
            name='duenger',
            options={'verbose_name': 'D\xfcnger', 'verbose_name_plural': 'D\xfcnger'},
        ),
        migrations.AlterModelOptions(
            name='duengungsstufe',
            options={'verbose_name': 'D\xfcngungsstufe', 'verbose_name_plural': 'D\xfcngungsstufe'},
        ),
        migrations.AlterModelOptions(
            name='satz',
            options={'verbose_name': 'Satz', 'verbose_name_plural': 'S\xe4tze'},
        ),
        migrations.AddField(
            model_name='satz',
            name='end_woche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Endwoche Menge'),
        ),
        migrations.AddField(
            model_name='satz',
            name='start_woche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Startwoche Menge'),
        ),
        migrations.AlterField(
            model_name='satz',
            name='duenger_kg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='D\xfcnger kg %10N'),
        ),
    ]
