# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jordbruksmark', '0002_auto_20161217_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wochen_menge',
            options={'verbose_name': 'Wochen Menge', 'verbose_name_plural': 'Wochen Mengen'},
        ),
    ]
